CREATE TEMPORARY TABLE temp AS
SELECT *
FROM hirings;

DROP TABLE hirings;

CREATE TABLE hirings (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER,
	book_id INTEGER,
	created_at DATETIME,
	returned_to DATETIME,
	CONSTRAINT hirings_books FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT hirings_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO hirings
SELECT *
FROM temp;

DROP TABLE temp;